# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-10 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20170712_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='card_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
