# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-12 01:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrument', '0002_auto_20170711_1430'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instrument',
            old_name='charge_type',
            new_name='chargeType',
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='chinese_name',
            field=models.CharField(blank=True, max_length=1024, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='english_name',
            field=models.CharField(blank=True, max_length=1024, null=True, unique=True),
        ),
    ]
