# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-12 02:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instrument', '0003_auto_20170712_0959'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instrument',
            old_name='reservation_end_time',
            new_name='reservationEndTime',
        ),
        migrations.RenameField(
            model_name='instrument',
            old_name='reservation_start_time',
            new_name='reservationStartTime',
        ),
        migrations.RenameField(
            model_name='instrument',
            old_name='reservation_time_unit',
            new_name='reservationTimeUnit',
        ),
        migrations.RenameField(
            model_name='instrument',
            old_name='reservation_type',
            new_name='reservationType',
        ),
        migrations.RenameField(
            model_name='instrument',
            old_name='sci_discount',
            new_name='sciDiscount',
        ),
        migrations.RenameField(
            model_name='manufacturer',
            old_name='chinese_name',
            new_name='chineseName',
        ),
        migrations.RenameField(
            model_name='manufacturer',
            old_name='english_name',
            new_name='englishName',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='end_time',
            new_name='endTime',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='start_time',
            new_name='startTime',
        ),
    ]
