# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-12 02:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instrument', '0004_auto_20170712_1001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instrument',
            old_name='chargeType',
            new_name='charge_type',
        ),
        migrations.RenameField(
            model_name='instrument',
            old_name='reservationEndTime',
            new_name='reservation_end_time',
        ),
        migrations.RenameField(
            model_name='instrument',
            old_name='reservationStartTime',
            new_name='reservation_start_time',
        ),
        migrations.RenameField(
            model_name='instrument',
            old_name='reservationTimeUnit',
            new_name='reservation_time_unit',
        ),
        migrations.RenameField(
            model_name='instrument',
            old_name='reservationType',
            new_name='reservation_type',
        ),
        migrations.RenameField(
            model_name='instrument',
            old_name='sciDiscount',
            new_name='sci_discount',
        ),
        migrations.RenameField(
            model_name='manufacturer',
            old_name='chineseName',
            new_name='chinese_name',
        ),
        migrations.RenameField(
            model_name='manufacturer',
            old_name='englishName',
            new_name='english_name',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='endTime',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='startTime',
            new_name='start_time',
        ),
    ]
