# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-10 11:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instrument', '0005_auto_20170712_1012'),
    ]

    operations = [
        migrations.CreateModel(
            name='IotClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='instrument',
            name='need_reservation',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='instrument.Department'),
        ),
        migrations.AddField(
            model_name='iotclient',
            name='instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instrument.Instrument'),
        ),
    ]
