# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-10 17:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instrument', '0008_instrumenthistoty'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InstrumentHistoty',
            new_name='InstrumentRecord',
        ),
    ]
