# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-11 15:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instrument', '0010_instrumentrecord_iotclient'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instrumentrecord',
            options={'ordering': ['-start_time']},
        ),
        migrations.RenameField(
            model_name='instrumentrecord',
            old_name='iotClient',
            new_name='iot_client',
        ),
    ]
